import { IBarbecue } from '../interfaces/list.inteface';

export const initList: IBarbecue[] = [
  {
    date: '01/12/23',
    title: 'Níver do Gui',
    total: 250,
    people: [
      {
        name: 'Alice',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Beto',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego B.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego P.',
        value: 10,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Fernando',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Gabriel',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Leonardo',
        value: 20,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Marcus J.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Michele',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Paulo',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Rafael S.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ralf',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ruan',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Thales',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Wait',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
    ],
  },
  {
    date: '23/12/23',
    title: 'Final de Ano',
    total: 250,
    people: [
      {
        name: 'Alice',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Beto',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego B.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego P.',
        value: 10,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Fernando',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Gabriel',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Leonardo',
        value: 20,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Marcus J.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Michele',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Paulo',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Rafael S.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ralf',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ruan',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Thales',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Wait',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
    ],
  },
  {
    date: '03/01/24',
    title: 'Sem motivo',
    total: 250,
    people: [
      {
        name: 'Alice',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Beto',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego B.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Diego P.',
        value: 10,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Fernando',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Gabriel',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Leonardo',
        value: 20,
        confirmed: false,
        alcoholicDrink: false,
      },
      {
        name: 'Marcus J.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Michele',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Paulo',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Rafael S.',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ralf',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Ruan',
        value: 20,
        confirmed: true,
        alcoholicDrink: true,
      },
      {
        name: 'Thales',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
      {
        name: 'Wait',
        value: 20,
        confirmed: false,
        alcoholicDrink: true,
      },
    ],
  },
];
