import { Raleway } from 'next/font/google';
import './globals.css';
import NextAuthSessionProvider from '@/providers/sessionProvider';
// import { FiscoDatalUIControllerProvider } from '@/shared/contexts/theme.context';
import ThemeRegistry from '@/shared/configs/ThemeRegistry';
import { Metadata } from 'next';
import StyledComponentsRegistry from '@/shared/configs/StyledComponentRegistry';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-br">
      <body className={raleway.className}>
        <ThemeRegistry>
          <StyledComponentsRegistry>
            {/* <FiscoDatalUIControllerProvider> */}
            <NextAuthSessionProvider>{children}</NextAuthSessionProvider>
            {/* </FiscoDatalUIControllerProvider> */}
          </StyledComponentsRegistry>
        </ThemeRegistry>
      </body>
    </html>
  );
}
